/*
  FE Runtime Env Builder
  ------------------------------------------------------------
  Vercel doesn't automatically expose env vars to a plain static frontend.
  This build step writes /core/runtime-env.js from process.env.

  Expected env vars (set in Vercel):
    - SUPABASE_URL
    - SUPABASE_ANON_KEY
    - FE_ENV_NAME (optional, e.g. "prod" or "stage")

  Safe: Supabase anon key is public by design; keep service role keys out.
*/

import fs from "fs";
import path from "path";

const root = process.cwd();
const outFile = path.join(root, "core", "runtime-env.js");

function esc(s) {
  return String(s || "").replaceAll("\\", "\\\\").replaceAll("`", "\\`");
}

const env = {
  SUPABASE_URL: process.env.SUPABASE_URL || "",
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || "",
  FE_ENV_NAME: process.env.FE_ENV_NAME || "unknown",
};

const content = `// FreedomEngine Runtime Environment (generated)
// ------------------------------------------------------------
// Generated by scripts/build-env.js at build/deploy time.
//
// DO NOT EDIT THIS FILE MANUALLY.

window.FE_ENV = window.FE_ENV || {
  SUPABASE_URL: \`${esc(env.SUPABASE_URL)}\`,
  SUPABASE_ANON_KEY: \`${esc(env.SUPABASE_ANON_KEY)}\`,
  FE_ENV_NAME: \`${esc(env.FE_ENV_NAME)}\`,
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content, "utf8");

console.log("[FE] wrote", outFile);
